name: Deploy to Staging

on:
  push:
    branches:
      - main

env:
  ACR_NAME: alattar
  ACR_LOGIN_SERVER: alattar-hygkehhmfvekb0fy.azurecr.io
  CONTAINER_APP_NAME: ca-cloudmediahub-api-staging
  RESOURCE_GROUP: rg-cloudmediahub-staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Staging
        run: |
          IMAGE_TAG=dev-latest
          az containerapp update \
            --name $CONTAINER_APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --image $ACR_LOGIN_SERVER/cloudmediahub-api:dev-latest

      - name: Promote image to staging-latest
        run: |
          az acr import \
          --name $ACR_NAME \
          --source $ACR_LOGIN_SERVER/cloudmediahub-api:dev-latest \
          --image cloudmediahub-api:staging-latest \
          --force